// client/src/app/shared/line-chart/line-chart.component.ts
import { Component, Input, OnInit, ViewChild, OnChanges, ElementRef, HostListener } from "@angular/core";
import * as d3 from "d3";

export interface LineChartLine {
    color?: string;
    data: LineChartData[]
}

export interface LineChartData {
    date: Date;
    point: number;
}

const MARGIN = 30;

interface MinMax<T> {
    min: T;
    max: T;
}

interface XY<t1, t2> {
    x: t1,
    y: t2
}

@Component({
    selector: "sh-line-chart",
    templateUrl: "./line-chart.component.html",
    styleUrls: ["./line-chart.component.scss"]
})
export class LineChartComponent implements OnInit, OnChanges {

    @ViewChild("container") private _containerRef: ElementRef;

    @HostListener('window:resize', ['$event'])
    onResize(event: Event) {
        // set fading flag to fadeout the container
        // during the resize
        if (this._timeoutHandle === null) {
            this.fading = true;
        }

        // Be lazy on resize and trigger action only
        // if user has not triggered two resize events in
        // 200ms interval
        clearTimeout(this._timeoutHandle);
        this._timeoutHandle = setTimeout(() => {
            this._removeChart();
            this._createChart();

            if (this.data) {
                // Update chart but do not animate
                this._updateChart(false);
            }

            // Show container after resize is over
            this.fading = false;

            this._timeoutHandle = null;
        }, 200);
    }

    @Input() data: LineChartLine[];
    @Input() height: number = 250;

    public fading: boolean = false;

    private _container: HTMLDivElement;
    private _svg: d3.Selection<any, any, any, any> = null;
    private _mainGroup: d3.Selection<any, any, any, any>;

    private _timeoutHandle: any = null;
    private _width: number;
    private _height: number;
    private _scaleX: d3.ScaleTime<number, number>;
    private _scaleY: d3.ScaleLinear<number, number>;
    private _axisX: any;
    private _axisY: any;

    constructor() { }

    public ngOnInit() {
        this._createChart();
        if (this.data) {
            this._updateChart();
        }
    }

    public ngOnChanges() {
        if (this._mainGroup) {
            this._updateChart();
        }
    }

    private _createChart() {
        this._container = this._containerRef.nativeElement as HTMLDivElement;

        this._width = this._container.offsetWidth - MARGIN * 2;
        this._height = this.height - MARGIN * 2;

        this._svg = d3.select(this._container).append("svg")
            .attr('width', this._container.offsetWidth)
            .attr('height', this.height);

        this._mainGroup = this._svg.append("g")
            .attr('transform', `translate(${MARGIN}, ${MARGIN})`);

        const domains = this._getDomains();

        this._scaleX = d3.scaleTime().domain(domains.x).rangeRound([0, this._width]);
        this._scaleY = d3.scaleLinear().domain(domains.y).rangeRound([this._height, 0]);

        this._axisX = this._svg.append("g")
            .attr("transform", `translate(${MARGIN}, ${MARGIN + this._height})`)
            .call(d3.axisBottom(this._scaleX));

        this._axisY = this._svg.append("g")
            .attr("class", "line-chart-y-group")
            .attr("transform", `translate(${MARGIN}, ${MARGIN})`)
            .call(this._getAxisLeft());
    }

    private _removeChart() {
        this._svg.remove();
        this._svg = null;
    }

    private _updateChart(animate: boolean = true) {
        // Update domains
        const domains = this._getDomains();
        this._scaleX.domain(domains.x);
        this._scaleY.domain(domains.y);

        // Update axises
        this._axisX.transition()
            .call(d3.axisBottom(this._scaleX));
        this._axisY.transition()
            .call(this._getAxisLeft());

        const data = this.data.map(l => l.data);
        const update = this._mainGroup
            .selectAll('.line-chart-path')
            .data(data);

        update.exit().remove();

        // Update existing lines 
        let selection = this._mainGroup.selectAll(".line-chart-path")
        if (animate) {
            selection
                .transition()
                .duration(750)
                .attr('d', this._getLine());
        } else {
            selection.attr('d', this._getLine());
        }

        // When new lines are inserted to the data -array,
        // append new path and draw a line
        selection = update.enter()
            .append("path")
            .attr('class', 'line-chart-path');

        if (animate) {
            selection
                .attr('d', this._getLine(this._height) as any)
                .transition()
                .duration(750)
                .attr('d', this._getLine());
        } else {
            selection.attr('d', this._getLine());
        }
    }

    private _getDomains(): XY<number[], number[]> {
        const dateBoundaries = this._getDateBoundaries();
        const domainX = [
            dateBoundaries.min.valueOf(),
            dateBoundaries.max.valueOf()
        ];

        const maxPoints = this._getMaxPoints() * 1.1;
        const domainY = [0, maxPoints];

        return {
            x: domainX,
            y: domainY
        }
    }

    private _getDateBoundaries(): MinMax<Date> {
        let dates: Date[] = [];
        let dateMsMap: number[] = [];

        this.data.forEach(line => {
            line.data.forEach(dataset => {
                let date = new Date(dataset.date.valueOf());
                date.setHours(0, 0, 0, 0);

                let ms = date.valueOf();
                if (dateMsMap.indexOf(ms) === -1) {
                    dates.push(date);
                    dateMsMap.push(ms);
                }
            });
        });

        dates.sort((d1, d2) => d1.valueOf() - d2.valueOf());

        return {
            min: new Date(dates[0].valueOf()),
            max: new Date(dates[dates.length - 1].valueOf())
        }
    }

    private _getMaxPoints(): number {
        let max = 0;

        this.data.forEach(line => {
            line.data.forEach(dataset => {
                if (dataset.point > max) {
                    max = dataset.point;
                }
            });
        });

        return max;
    }

    private _getAxisLeft(): d3.Axis<number | { valueOf(): number; }> {
        return d3.axisLeft(this._scaleY).tickPadding(7).tickSize(-this._container.offsetWidth + 2 * MARGIN)
    }

    private _getLine(fixedYPos?: number): d3.Line<[number, number]> {
        return d3.line()
            .x((d: any, index: number) => {
                const data = d as LineChartData;
                return this._scaleX(data.date.valueOf());
            })
            .y((d: any) => {
                if (fixedYPos !== undefined) {
                    return fixedYPos
                }

                const data = d as LineChartData;
                return this._scaleY(data.point);
            });
    }
}
<div #container [style.height]="height" class="line-chart-container" [class.line-chart-container--fading]="fading">
    <div #tooltipContainer *ngIf="!!activeItem" class="line-chart-tooltip-container">
        <div class="line-chart-tooltip">
            <ng-template *ngIf="!!tooltipTemplate" [ngTemplateOutlet]="tooltipTemplate" [ngOutletContext]="{date: activeItem.date, point: activeItem.point}"></ng-template>
            <div *ngIf="!tooltipTemplate">
                <h4 class="line-chart-tooltip-header">{{ formatDate(activeItem.date) }}</h4>
                <p class="line-chart-tooltip-body">{{ activeItem.point.toFixed(2) }} km</p>
            </div>
        </div>
    </div>
</div>

// client/src/app/components/line-chart/line-chart.tsx
import * as React from "react";
import * as d3 from "d3";
import * as classNames from "classnames";

const styles: any = require("./line-chart.css");

export interface LineChartLine {
    color: string;
    data: LineChartPoint[];
}

export interface LineChartPoint {
    date: Date;
    value: number;
}

interface OwnProps {
    height?: number;
    lines: LineChartLine[];
}

interface OwnState {
    fading: boolean;
}

interface MinMax<T> {
    min: T;
    max: T;
}

interface XY<t1, t2> {
    x: t1,
    y: t2
}

const MARGIN = 30;

type D3Element = d3.Selection<d3.BaseType, {}, null, undefined>;

export class LineChart extends React.Component<OwnProps, OwnState> {

    static defaultProps: Partial<OwnProps> = {
        height: 250
    }

    private _timeoutHandle: any;

    private _containerRef: HTMLDivElement = null;

    private _svg: D3Element = null;
    private _mainG: D3Element = null;
    private _pathsG: D3Element = null;
    private _scales: XY<d3.ScaleTime<number, number>, d3.ScaleLinear<number, number>> = { x: null, y: null };
    private _axes: XY<D3Element, D3Element> = { x: null, y: null };

    constructor(props) {
        super(props);

        this.state = {
            fading: false
        }

        this._handleWindowResize = this._handleWindowResize.bind(this);
    }

    public render(): JSX.Element {
        const classes = classNames({
            [styles.root]: true,
            [styles.fading]: this.state.fading
        });

        return (
            <div ref={(ref => this._containerRef = ref)} className={classes} style={{ height: this.props.height }}></div>
        );
    }

    public componentDidUpdate() {
        this._updateChart();
    }

    public componentWillMount() {
        window.addEventListener("resize", this._handleWindowResize);
    }

    public componentWillUnmount() {
        window.removeEventListener("resize", this._handleWindowResize);
    }

    public componentDidMount() {
        this._createChart();
        this._updateChart();
    }

    private _createChart() {
        const self = this;

        const containerOffsetWidth = this._containerRef.offsetWidth;

        this._svg = d3.select(this._containerRef).append("svg")
            .attr('height', this.props.height)
            .attr('width', "100%");


        this._mainG = this._svg.append("g")
            .attr('transform', `translate(0, 0)`);

        this._pathsG = this._mainG.append("g")
            .attr("transform", `translate(${MARGIN}, ${MARGIN})`)

        const domains = this._getDomains();
        const width = containerOffsetWidth - MARGIN * 2;
        const height = this._getInnerHeight();

        this._scales.x = d3.scaleTime().domain(domains.x).rangeRound([0, width]);
        this._scales.y = d3.scaleLinear().domain(domains.y).rangeRound([height, 0]);

        this._axes.x = this._mainG.append("g")
            .attr("class", styles.axisGroup)
            .attr("transform", `translate(${MARGIN}, ${MARGIN + height})`)
            .call(d3.axisBottom(this._scales.x).ticks(4));

        this._axes.y = this._mainG.append("g")
            .attr("class", styles.axisGroup)
            .attr("transform", `translate(${MARGIN}, ${MARGIN})`)
            .call(this._getAxisLeft());
    }

    private _updateChart(animate: boolean = true) {


        const domains = this._getDomains();
        this._scales.x.domain(domains.x);
        this._scales.y.domain(domains.y);

        this._axes.x.transition().call(d3.axisBottom(this._scales.x).ticks(4) as any);
        this._axes.y.transition().call(this._getAxisLeft() as any);

        const data = this.props.lines.map(line => line.data);

        const update = this._pathsG.selectAll(`.${styles.linePath}`).data(data);
        update.exit().remove();

        const existingLines = this._pathsG.selectAll(`.${styles.linePath}`);

        if (animate) {
            existingLines.transition().duration(750).attr("d", this._getLine());
        } else {
            existingLines.attr("d", this._getLine());
        }

        const newLines = update.enter().append("path").attr("class", styles.linePath);
        if (animate) {
            newLines.attr("d", this._getLine(this._getInnerHeight()) as any)
                .transition()
                .duration(750)
                .attr("d", this._getLine() as any)
        } else {
            newLines.attr("d", this._getLine() as any);
        }
    }

    private _removeChart() {
        this._svg.remove();
        this._svg = null;
    }

    private _handleWindowResize() {
        // Fade out the component when resize event is triggered
        if (this._timeoutHandle === null) {
            this.setState({ fading: true });
        }

        // Be lazy
        clearTimeout(this._timeoutHandle);
        this._timeoutHandle = setTimeout(() => {
            this._removeChart();
            this._createChart();
            this._updateChart(false);

            // Show container after resize is over
            this.setState({ fading: false });

            this._timeoutHandle = null;
        }, 200);
    }

    private _getLine(fixedYPos?: number): d3.Line<[number, number]> {
        return d3.line()
            .curve(d3.curveCatmullRom.alpha(1))
            .x((d: any) => {
                const data = d as LineChartPoint;
                return this._scales.x(data.date.valueOf());
            })
            .y((d: any) => {
                if (fixedYPos !== undefined) {
                    return fixedYPos
                }

                const data = d as LineChartPoint;
                return this._scales.y(data.value);
            });
    }

    private _getInnerHeight(): number {
        return this.props.height - MARGIN * 2;
    }

    private _getDomains(): XY<number[], number[]> {
        const dateBoundaries = this._getDateBoundaries();
        const domainX = [
            dateBoundaries.min.valueOf(),
            dateBoundaries.max.valueOf()
        ];

        const maxPoints = this._getMaxValue() * 1.1;
        const domainY = [0, maxPoints];

        return {
            x: domainX,
            y: domainY
        }
    }

    private _getDateBoundaries(): MinMax<Date> {
        const dates: Date[] = [];
        const dateMsMap: number[] = [];

        this.props.lines.forEach(line => {
            line.data.forEach(dataset => {
                const date = new Date(dataset.date.valueOf());
                date.setHours(0, 0, 0, 0);

                const ms = date.valueOf();
                if (dateMsMap.indexOf(ms) === -1) {
                    dates.push(date);
                    dateMsMap.push(ms);
                }
            });
        });

        dates.sort((d1, d2) => d1.valueOf() - d2.valueOf());

        return {
            min: new Date(dates[0].valueOf()),
            max: new Date(dates[dates.length - 1].valueOf())
        }
    }

    private _getMaxValue(): number {
        let max = 0;
        this.props.lines.forEach(line => {
            line.data.forEach(dataset => max = Math.max(dataset.value, max))
        });
        return max;
    }

    private _getAxisLeft(): d3.Axis<number | { valueOf(): number; }> {
        return d3.axisLeft(this._scales.y).tickPadding(7).tickSize(-this._containerRef.offsetWidth + 2 * MARGIN);
    }

}
